### ISSUE TITLE
C++ version of this project?

### ISSUE THREAD

**Issue by jjqcat** [KyushuUniversityMathematics/PolyArcFitter#2]
Would you provide another version C++?

**Comment by shizuo-kaji** [comment]
Currently we have no plans for a C++ port, as the python version runs sufficiently fast. Do you have any speed issue? If so, can you provide an example?

**Comment by jjqcat** [comment]
Hi, 
     any document of PolyArcFitter in English?  sorry, I'm not familiar with Python program.
------------------------------------------------------------------
发件人：Shizuo KAJI <notifications@github.com>
发送时间：2018年12月30日(星期日) 20:57
收件人：KyushuUniversityMathematics/PolyArcFitter <PolyArcFitter@noreply.github.com>
抄　送：蒋金权 <jiang.j.q@tizer.com.cn>; Author <author@noreply.github.com>
主　题：Re: [KyushuUniversityMathematics/PolyArcFitter] C++ version of this project? (#2)

Currently we have no plans for a C++ port, as the python version runs sufficiently fast. Do you have any speed issue? If so, can you provide an example?

**Comment by shizuo-kaji** [comment]
python arc_fitter.py -h 
gives you a brief description of command-line arguments.
Also, arc_fitter.py contains a fair amount of comments in English.
Please first look at them and ask me if you have any questions.
